// Generated by CoffeeScript 1.7.1
var activeDir, app, bodyParser, cluster, config, cookieParser, cpuCount, express, fs, i, path, routes, staticDir, viewsRoot, _i;

cluster = require('cluster');

path = require('path');

express = require('express');

config = require('./config').config;

routes = require('./routes');

fs = require('fs');

if (cluster.isMaster) {
  cpuCount = require('os').cpus().length;
  for (i = _i = 0; 0 <= cpuCount ? _i <= cpuCount : _i >= cpuCount; i = 0 <= cpuCount ? ++_i : --_i) {
    cluster.fork();
  }
  cluster.on('exit', function(worker) {
    console.log("worker" + worker.id + " died :(");
    return cluster.fork();
  });
} else {
  app = express();
  cookieParser = require('cookie-parser');
  bodyParser = require('body-parser');
  app.use(cookieParser());
  app.use(bodyParser.urlencoded({
    extended: true
  }));
  app.use(bodyParser.json());
  viewsRoot = path.join(__dirname, 'view');
  app.set('views', viewsRoot);
  app.set('view engine', 'jade');
  app.use(function(req, res, next) {
    res.locals.config = config;
    return next();
  });
  staticDir = path.join(__dirname, 'public');
  activeDir = path.join(__dirname, 'active');
  app.use(express["static"](staticDir));
  app.use(express["static"](activeDir));
  routes(app);
  app.listen(config.port, config.ip);
  console.log("Node Web Start. " + cluster.worker.id);
}
