// Generated by CoffeeScript 1.7.1
var admin, home;

home = require('./controllers/home');

admin = require('./controllers/admin');

module.exports = function(app) {
  app.get('/', home.index);
  app.get('/success', home.success);
  app.post("/regs", home.post);
  app.get('/admin/*', admin.before);
  app.get('/admin/in', admin["in"]);
  app.get('/admin/next', admin.next);
  app.get('/admin/dealer', admin.dealer);
  app.post('/admin/dealer/reser/:user_id', admin.dealerreser);
  app.get('/admin/dealer/active', admin.dealeractive);
  app.get('/admin/dealer/info', admin.dealerinfo);
  app.post('/admin/dealer/infopost', admin.dealerinfopost);
  return app.post('/admin/in', admin.inpost);
};

console.log("routes loaded.");
