// Generated by CoffeeScript 1.7.1
var admin, home;

home = require('./controllers/home');

admin = require('./controllers/admin');

module.exports = function(app) {
  return app.get('*', home.notfind);
};
