// Generated by CoffeeScript 1.7.1
var Dealer, models;

models = require('./base');

Dealer = models.Dealer;

exports.login = function(dealer, password, callback) {
  return Dealer.findOne({
    dealer_id: dealer,
    password: password
  }, callback);
};

exports["new"] = function(province, city, id, password, name, adr, callback) {
  var d;
  d = new Dealer();
  d.province = province;
  d.city = city;
  d.dealer_id = id;
  d.password = password;
  d.dealer = name;
  d.adr = adr;
  return d.save(callback);
};
