// Generated by CoffeeScript 1.7.1
var Lots, User, models;

models = require('./base');

Lots = models.Lots;

User = models.User;

exports.used = function(callback) {
  return User.aggregate({
    $group: {
      _id: {
        lot: "$lot",
        cartype: "$cartype"
      },
      total: {
        $sum: 1
      }
    }
  }).exec(callback);
};

exports.count = function(callback) {
  return Lots.find({}, callback);
};

exports.getById = function(id, callback) {
  return Lots.findById(id, callback);
};

exports["new"] = function(data, callback) {
  var l;
  l = new Lots();
  l.lotname = data.lotname;
  l.description = data.description;
  l.cartype = data.cartype;
  l.nums = data.nums;
  return l.save(callback);
};
