// Generated by CoffeeScript 1.7.1
var DealerSchema, ObjectId, Schema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

ObjectId = Schema.ObjectId;

DealerSchema = new Schema({
  dealer_id: {
    type: String,
    index: true
  },
  password: {
    type: String
  },
  dealer: {
    type: String
  },
  province: {
    type: String
  },
  city: {
    type: String
  },
  adr: {
    type: String
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

mongoose.model('Dealer', DealerSchema);
