// Generated by CoffeeScript 1.7.1
var ObjectId, Schema, ServSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

ObjectId = Schema.ObjectId;

ServSchema = new Schema({
  username: {
    type: String
  },
  password: {
    type: String
  },
  type: {
    type: Number
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

mongoose.model('Serv', ServSchema);
