// Generated by CoffeeScript 1.7.1
var ObjectId, Schema, UserSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

ObjectId = Schema.Types.ObjectId;

UserSchema = new Schema({
  code: {
    type: String,
    index: true
  },
  username: {
    type: String
  },
  mobile: {
    type: String
  },
  othername: {
    type: String
  },
  othermobile: {
    type: String
  },
  customer: {
    type: String
  },
  mileage: {
    type: String
  },
  from: {
    type: Number
  },
  changed: {
    type: Boolean,
    "default": false
  },
  cartype: {
    type: String
  },
  lot: {
    type: ObjectId,
    ref: "Lots"
  },
  tenoff: {
    type: Boolean,
    "default": false
  },
  thirtytwo: {
    type: String
  },
  thir: [
    {
      type: String
    }
  ],
  usedbynine: {
    type: Boolean,
    "default": false
  },
  province: {
    type: String
  },
  city: {
    type: String
  },
  dealer: {
    type: String
  },
  dealer_name: {
    type: String
  },
  vin: {
    type: String
  },
  imp_at: {
    type: Date
  },
  reser_at: {
    type: Date
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

mongoose.model('User', UserSchema);
